export type Locale = 'fr' | 'ar' | 'en';
export type LocalizedText = Partial<Record<Locale, string>>;
export type Category = { id: string; name: string; position: number; available?: boolean; translations?: LocalizedText };
export type Product = {
  id: string; categoryId: string; name: string; description?: string; price: number;
  image?: string; available: boolean; translations?: LocalizedText;
  descriptions?: LocalizedText;
};
export const copyText = {
  fr: { tagline:'Un café, une parenthèse.', intro:'Une carte de maison, des classiques choisis et le goût de prendre son temps.', address:'Tunis, Tunisie', hours:'Tous les jours · 06:00–01:00', open:'Tous les jours · 06:00–01:00', closed:'Actuellement indisponible', unavailable:'Indisponible pour le moment', search:'Chercher dans la carte', menu:'La carte', all:'Tout', contact:'Nous trouver', follow:'Suivez la maison', hoursTitle:'Horaires', detail:'À propos de ce produit', loading:'La carte arrive…', noResults:'Rien ne correspond à votre recherche.', footer:'La carte LASTRADA Café-Resto.', cached:'Carte consultée hors connexion', adminEntry:'Éditeur de la carte', close:'Fermer', itinerary:'Ouvrir dans Google Maps', phoneTitle:'Téléphone', phonePlaceholder:'+216 51 524 107', socialTitle:'Réseaux sociaux', socialPlaceholder:'Compte à renseigner', addressTitle:'Adresse' },
  ar: { tagline:'قهوة واستراحة.', intro:'قائمة من الدار، أطباق مختارة ومتعة الاستمتاع بالوقت.', address:'تونس، تونس', hours:'يومياً · 06:00–01:00', open:'يومياً · 06:00–01:00', closed:'غير متاح حالياً', unavailable:'غير متوفر الآن', search:'ابحث في القائمة', menu:'القائمة', all:'الكل', contact:'زورونا', follow:'تابعوا الدار', hoursTitle:'أوقات العمل', detail:'عن هذا المنتج', loading:'القائمة قادمة…', noResults:'لا توجد نتائج مطابقة لبحثك.', footer:'قائمة لاستـرادا كافيه ريستو.', cached:'القائمة متاحة دون اتصال', adminEntry:'محرر القائمة', close:'إغلاق', itinerary:'افتح في خرائط Google', phoneTitle:'الهاتف', phonePlaceholder:'+216 51 524 107', socialTitle:'التواصل الاجتماعي', socialPlaceholder:'الحساب سيُضاف لاحقاً', addressTitle:'العنوان' },
  en: { tagline:'Coffee, then a little pause.', intro:'A house menu, familiar favourites and the pleasure of taking your time.', address:'Tunis, Tunisia', hours:'Daily · 06:00–01:00', open:'Daily · 06:00–01:00', closed:'Temporarily unavailable', unavailable:'Not available right now', search:'Search the menu', menu:'The menu', all:'All', contact:'Find us', follow:'Follow along', hoursTitle:'Opening hours', detail:'About this product', loading:'The menu is on its way…', noResults:'Nothing matches your search.', footer:'The LASTRADA Café-Resto menu.', cached:'Menu available offline', adminEntry:'Menu editor', close:'Close', itinerary:'Open in Google Maps', phoneTitle:'Phone', phonePlaceholder:'+216 51 524 107', socialTitle:'Social', socialPlaceholder:'Account to be provided', addressTitle:'Address' },
} as const;

export const adminText = {
  fr: { editor:'GESTION DU MENU · LASTRADA', categories:'Les rubriques', products:'Les produits', preview:'Aperçu client', tabCategories:'Catégories', tabProducts:'Produits', tabPreview:'Aperçu', add:'Ajouter', order:'Utilisez les flèches pour réordonner les rubriques.', productNote:'Prix en dinars tunisiens · carte sans commande.', sections:'Rubriques de la carte', items:'produits', position:'position', available:'Disponible', unavailable:'Masqué', view:'Voir la carte', installTitle:'Votre carte, à portée de pouce.', installBody:'Ajoutez LASTRADA à l’écran d’accueil depuis le menu de votre navigateur.', loginEyebrow:'ESPACE ADMINISTRATEUR', loginTitle:'La carte, à portée de main.', loginBody:'Connectez-vous pour gérer les rubriques et les produits de votre carte.', email:'Adresse e-mail', password:'Mot de passe', loginHint:'', enter:'Ouvrir la gestion', back:'Retour à la carte', addCategory:'Ajouter une catégorie', editCategory:'Modifier la catégorie', newCategory:'Nouvelle catégorie', categoryName:'Nom en français', categoryNote:'Les traductions restent conservées pour les catégories déjà présentes. Les nouvelles catégories apparaissent en français dans les autres langues.', emptyCategory:'Aucune catégorie. Ajoutez la première.', deleteCategory:'Supprimer cette catégorie ?', deleteProduct:'Supprimer ce produit ?', removedCategory:'La catégorie et ses produits seront retirés de la carte.', removedProduct:'Le produit sera retiré de la carte.', cancel:'Annuler', save:'Enregistrer', editProduct:'Modifier le produit', newProduct:'Nouveau produit', image:'Ajouter ou remplacer la photo', removeImage:'Supprimer la photo', imageNote:'La photo est recadrée en aperçu WebP de 800 px et enregistrée avec le menu.', name:'Nom en français', price:'Prix · TND', category:'Catégorie', description:'Description', descriptionHint:'Une phrase, quelques saveurs.', availableToggle:'Afficher sur la carte', confirm:'CONFIRMATION', delete:'Supprimer', noProducts:'Aucun produit pour le moment.', createCategoryFirst:'Créez une catégorie avant d’ajouter un produit.', createCategory:'Créer une catégorie', previewTitle:'À quoi ressemble la carte', previewBody:'La vue visiteur, avec vos changements.', moveFirst:'Mettre en premier', quickAdd:'Ajouter un produit', loading:'Chargement…' },
  en: { editor:'MENU MANAGEMENT · LASTRADA', categories:'Categories', products:'Products', preview:'Customer preview', tabCategories:'Categories', tabProducts:'Products', tabPreview:'Preview', add:'Add', order:'Use the arrows to reorder categories.', productNote:'Prices in Tunisian dinars · browsing only.', sections:'Menu categories', items:'products', position:'position', available:'Available', unavailable:'Hidden', view:'View menu', installTitle:'Your menu, close at hand.', installBody:'Add LASTRADA to your home screen from your browser menu.', loginEyebrow:'ADMINISTRATOR ACCESS', loginTitle:'Your menu, close at hand.', loginBody:'Sign in to manage the categories and products on your menu.', email:'Email address', password:'Password', loginHint:'', enter:'Open menu manager', back:'Back to the menu', addCategory:'Add category', editCategory:'Edit category', newCategory:'New category', categoryName:'Name in French', categoryNote:'Translations remain for existing categories. New categories appear in French in other languages.', emptyCategory:'No categories yet. Add the first one.', deleteCategory:'Delete this category?', deleteProduct:'Delete this product?', removedCategory:'The category and its products will be removed from the menu.', removedProduct:'The product will be removed from the menu.', cancel:'Cancel', save:'Save changes', editProduct:'Edit product', newProduct:'New product', image:'Choose or replace photo', removeImage:'Remove photo', imageNote:'The photo is cropped to an 800 px WebP preview and stored with the menu.', name:'Name in French', price:'Price · TND', category:'Category', description:'Description', descriptionHint:'A line or two about the flavours.', availableToggle:'Show on the menu', confirm:'CONFIRMATION', delete:'Delete', noProducts:'No products here yet.', createCategoryFirst:'Create a category before adding products.', createCategory:'Create a category', previewTitle:'The menu as guests see it', previewBody:'Customer view with your changes.', moveFirst:'Move to first', quickAdd:'Add a product', loading:'Loading…' },
  ar: { editor:'إدارة القائمة · لاستـرادا', categories:'الفئات', products:'المنتجات', preview:'معاينة الزائر', tabCategories:'الفئات', tabProducts:'المنتجات', tabPreview:'معاينة', add:'إضافة', order:'استخدم الأسهم لإعادة ترتيب الفئات.', productNote:'الأسعار بالدينار التونسي · عرض القائمة فقط.', sections:'فئات القائمة', items:'منتجات', position:'الترتيب', available:'متوفر', unavailable:'مخفي', view:'عرض القائمة', installTitle:'قائمتك دائماً قريبة.', installBody:'أضف لاستـرادا إلى الشاشة الرئيسية من قائمة المتصفح.', loginEyebrow:'دخول المدير', loginTitle:'قائمتك في متناول يدك.', loginBody:'سجّل الدخول لإدارة الفئات والمنتجات في قائمتك.', email:'البريد الإلكتروني', password:'كلمة المرور', loginHint:'', enter:'فتح إدارة القائمة', back:'العودة إلى القائمة', addCategory:'إضافة فئة', editCategory:'تعديل الفئة', newCategory:'فئة جديدة', categoryName:'الاسم بالفرنسية', categoryNote:'تبقى الترجمات للفئات الموجودة. تظهر الفئات الجديدة بالفرنسية في اللغات الأخرى.', emptyCategory:'لا توجد فئات. أضف الأولى.', deleteCategory:'حذف هذه الفئة؟', deleteProduct:'حذف هذا المنتج؟', removedCategory:'ستُحذف الفئة ومنتجاتها من القائمة.', removedProduct:'سيُحذف المنتج من القائمة.', cancel:'إلغاء', save:'حفظ', editProduct:'تعديل المنتج', newProduct:'منتج جديد', image:'اختر صورة من هذا الجهاز', removeImage:'Delete image', imageNote:'تُقص الصورة إلى معاينة WebP بعرض 800 بكسل وتحفظ مع القائمة.', name:'الاسم بالفرنسية', price:'السعر · دينار', category:'الفئة', description:'الوصف', descriptionHint:'جملة عن النكهات.', availableToggle:'إظهار في القائمة', confirm:'تأكيد', delete:'حذف', noProducts:'لا توجد منتجات هنا بعد.', createCategoryFirst:'أنشئ فئة قبل إضافة المنتجات.', createCategory:'إنشاء فئة', previewTitle:'القائمة كما يراها الزوار', previewBody:'عرض الزوار مع تغييراتك.', moveFirst:'نقل إلى البداية', quickAdd:'إضافة منتج', loading:'جارٍ التحميل…' },
} as const;

export function translated(text: string, translations: LocalizedText | undefined, locale: Locale) {
  return (translations?.[locale] || text);
}
