export type Locale = 'fr' | 'ar' | 'en';
export type LocalizedText = Partial<Record<Locale, string>>;
export type Category = { id: string; name: string; position: number; translations?: LocalizedText };
export type Product = {
  id: string; categoryId: string; name: string; description?: string; price: number;
  image?: string; available: boolean; translations?: LocalizedText;
  descriptions?: LocalizedText;
};

export const seededCategories: Category[] = [
  { id: 'eau', name: 'Eau', position: 1000, translations: { ar: 'مياه', en: 'Water' } },
  { id: 'cafes', name: 'Cafés', position: 2000, translations: { ar: 'قهوة', en: 'Coffee' } },
  { id: 'cafes-froides', name: 'Cafés froides', position: 3000, translations: { ar: 'قهوة باردة', en: 'Iced coffee' } },
  { id: 'narguile', name: 'Narguilé (Chicha)', position: 4000, translations: { ar: 'أرجيلة (شيشة)', en: 'Hookah (Shisha)' } },
  { id: 'thes', name: 'Thés', position: 5000, translations: { ar: 'شاي', en: 'Tea' } },
  { id: 'boissons', name: 'Boissons', position: 6000, translations: { ar: 'مشروبات', en: 'Drinks' } },
  { id: 'patisseries', name: 'Pâtisseries', position: 7000, translations: { ar: 'حلويات', en: 'Pastries' } },
];
export const seededProducts: Product[] = [
  { id:'eau-plate',categoryId:'eau',name:'Eau minérale',description:'Eau plate fraîche, servie à votre convenance.',price:2.5,available:true,translations:{en:'Still mineral water',ar:'مياه معدنية عادية'},descriptions:{en:'Chilled still water, served just right.',ar:'مياه معدنية عادية باردة.'} },
  { id:'eau-gazeuse',categoryId:'eau',name:'Eau gazeuse',description:'Fine et pétillante, bien fraîche.',price:3.5,available:true,translations:{en:'Sparkling water',ar:'مياه غازية'},descriptions:{en:'Fine bubbles, served chilled.',ar:'فقاعات ناعمة، تقدم باردة.'} },
  { id:'eau-grand-format',categoryId:'eau',name:'Grande eau minérale',description:'Une bouteille à partager autour de la table.',price:4.5,available:true,translations:{en:'Large mineral water',ar:'مياه معدنية كبيرة'},descriptions:{en:'A bottle to share around the table.',ar:'قارورة للمشاركة حول الطاولة.'} },
  { id:'cafe-turc',categoryId:'cafes',name:'Café turc',description:'Moulu finement, préparé à la minute.',price:4.5,available:true,translations:{en:'Turkish coffee',ar:'قهوة تركية'},descriptions:{en:'Finely ground and brewed to order.',ar:'قهوة مطحونة ناعماً وتحضر عند الطلب.'} },
  { id:'espresso',categoryId:'cafes',name:'Espresso',description:'Court, intense, torréfié avec patience.',price:4,available:true,translations:{en:'Espresso',ar:'إسبريسو'},descriptions:{en:'Short, intense, patiently roasted.',ar:'قصير ومركز، محمص بعناية.'} },
  { id:'cappuccino',categoryId:'cafes',name:'Cappuccino',description:'Un espresso rond, lait velouté et cacao.',price:7.5,available:true,translations:{en:'Cappuccino',ar:'كابتشينو'},descriptions:{en:'A round espresso, silky milk and cocoa.',ar:'إسبريسو متوازن مع حليب ناعم ورشة كاكاو.'} },
  { id:'cafe-glace',categoryId:'cafes-froides',name:'Café glacé',description:'Espresso refroidi, glaçons et douceur légère.',price:7,available:true,translations:{en:'Iced coffee',ar:'قهوة مثلجة'},descriptions:{en:'Chilled espresso, ice and a gentle sweetness.',ar:'إسبريسو بارد مع الثلج ولمسة حلاوة.'} },
  { id:'latte-glace',categoryId:'cafes-froides',name:'Latte glacé',description:'Lait frais, espresso et glaçons.',price:8.5,available:true,translations:{en:'Iced latte',ar:'لاتيه مثلج'},descriptions:{en:'Cold milk, espresso and ice.',ar:'حليب بارد وإسبريسو وثلج.'} },
  { id:'frappe',categoryId:'cafes-froides',name:'Frappé café',description:'Café frappé, mousse légère et notes de cacao.',price:9,available:true,translations:{en:'Coffee frappe',ar:'فرابيه بالقهوة'},descriptions:{en:'Blended coffee, light foam and cocoa notes.',ar:'قهوة مخفوقة برغوة خفيفة ونكهة الكاكاو.'} },
  { id:'chicha-classique',categoryId:'narguile',name:'Chicha classique',description:'Préparation classique, parfum au choix.',price:22,available:true,translations:{en:'Classic shisha',ar:'شيشة كلاسيكية'},descriptions:{en:'A classic preparation, choose your flavour.',ar:'تحضير كلاسيكي، اختر النكهة.'} },
  { id:'chicha-pomme',categoryId:'narguile',name:'Double pomme',description:'Un parfum rond aux notes de pomme et d’anis.',price:24,available:true,translations:{en:'Double apple',ar:'تفاحتان'},descriptions:{en:'Round apple notes with a hint of anise.',ar:'نكهة تفاح متوازنة مع لمسة يانسون.'} },
  { id:'chicha-menthe',categoryId:'narguile',name:'Menthe fraîche',description:'Une fraîcheur nette, à savourer lentement.',price:24,available:true,translations:{en:'Fresh mint',ar:'نعناع منعش'},descriptions:{en:'Clear mint freshness, made to linger over.',ar:'انتعاش النعناع، للاستمتاع على مهل.'} },
  { id:'the-menthe',categoryId:'thes',name:'Thé à la menthe',description:'Thé vert, menthe fraîche et pignons de pin.',price:6.5,available:true,translations:{en:'Mint tea',ar:'شاي بالنعناع'},descriptions:{en:'Green tea, fresh mint and pine nuts.',ar:'شاي أخضر ونعناع طازج وصنوبر.'} },
  { id:'the-vert',categoryId:'thes',name:'Thé vert',description:'Thé vert délicat, servi nature.',price:5,available:true,translations:{en:'Green tea',ar:'شاي أخضر'},descriptions:{en:'Delicate green tea, served plain.',ar:'شاي أخضر ناعم يقدم سادة.'} },
  { id:'the-jasmine',categoryId:'thes',name:'Thé au jasmin',description:'Thé délicatement parfumé aux fleurs de jasmin.',price:6,available:true,translations:{en:'Jasmine tea',ar:'شاي بالياسمين'},descriptions:{en:'Tea gently scented with jasmine flowers.',ar:'شاي معطر برفق بأزهار الياسمين.'} },
  { id:'citronnade',categoryId:'boissons',name:'Citronnade fraîche',description:'Citrons pressés, une pointe de fleur d’oranger.',price:8,available:false,translations:{en:'Fresh lemonade',ar:'ليموناضة طازجة'},descriptions:{en:'Freshly squeezed lemons with orange blossom.',ar:'ليمون معصور طازجاً ولمسة من ماء الزهر.'} },
  { id:'jus-orange',categoryId:'boissons',name:'Jus d’orange frais',description:'Oranges pressées à la minute.',price:9,available:true,translations:{en:'Fresh orange juice',ar:'عصير برتقال طازج'},descriptions:{en:'Oranges pressed to order.',ar:'برتقال يعصر عند الطلب.'} },
  { id:'boisson-fraiche',categoryId:'boissons',name:'Boisson fraîche',description:'Une boisson pétillante, servie bien fraîche.',price:5.5,available:true,translations:{en:'Chilled soft drink',ar:'مشروب بارد'},descriptions:{en:'A sparkling soft drink, served chilled.',ar:'مشروب غازي يقدم بارداً.'} },
  { id:'makroud',categoryId:'patisseries',name:'Makroud',description:'Semoule dorée, dattes et filet de miel.',price:4.5,available:true,translations:{en:'Makroud',ar:'مقروض'},descriptions:{en:'Golden semolina, dates and a thread of honey.',ar:'سميد ذهبي، تمر ولمسة من العسل.'} },
  { id:'bambalouni',categoryId:'patisseries',name:'Bambalouni',description:'Beignet chaud, sucre fin, à savourer sans hâte.',price:5,available:true,translations:{en:'Bambalouni',ar:'بمبالوني'},descriptions:{en:'Warm doughnut, fine sugar, made to enjoy slowly.',ar:'دونات ساخنة وسكر ناعم، استمتع بها على مهل.'} },
  { id:'cake-orange',categoryId:'patisseries',name:'Cake à l’orange',description:'Gâteau moelleux et parfumé aux zestes d’orange.',price:6.5,available:true,translations:{en:'Orange cake',ar:'كيك البرتقال'},descriptions:{en:'Soft cake scented with orange zest.',ar:'كيك طري معطر بقشر البرتقال.'} },
];

const STORAGE_KEY = 'lastrada-menu-demo-v2';
type StoreState = { categories: Category[]; products: Product[] };
const copy = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
function readStore(): StoreState {
  if (typeof window === 'undefined') return { categories: copy(seededCategories), products: copy(seededProducts) };
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved) as StoreState;
      if (Array.isArray(parsed.categories) && Array.isArray(parsed.products)) return parsed;
    }
  } catch { /* A corrupt demo cache falls back to the bundled menu. */ }
  return { categories: copy(seededCategories), products: copy(seededProducts) };
}
function persist(state: StoreState) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch { /* local preview images may exceed browser storage quota */ }
}

/** Typed local demo repository: replace this boundary with an API repository later. */
export const menuRepository = {
  load(): StoreState { return readStore(); },
  save(state: StoreState) { persist(state); },
  reset(): StoreState {
    const state = { categories: copy(seededCategories), products: copy(seededProducts) };
    persist(state); return state;
  },
};

export const copyText = {
  fr: { tagline:'Un café, une parenthèse.', intro:'Une carte de maison, des classiques choisis et le goût de prendre son temps.', address:'Adresse à renseigner', hours:'Horaires à renseigner', open:'Horaires à renseigner', closed:'Actuellement indisponible', unavailable:'Indisponible pour le moment', search:'Chercher dans la carte', menu:'La carte', all:'Tout', contact:'Nous trouver', follow:'Suivez la maison', hoursTitle:'Horaires', detail:'À propos de ce produit', loading:'La carte arrive…', noResults:'Rien ne correspond à votre recherche.', footer:'La carte LASTRADA Café-Resto.', cached:'Carte consultée hors connexion', adminEntry:'Éditeur de la carte', close:'Fermer', itinerary:'Itinéraire à renseigner', phoneTitle:'Téléphone', phonePlaceholder:'Numéro à renseigner', socialTitle:'Réseaux sociaux', socialPlaceholder:'Compte à renseigner', addressTitle:'Adresse' },
  ar: { tagline:'قهوة واستراحة.', intro:'قائمة من الدار، أطباق مختارة ومتعة الاستمتاع بالوقت.', address:'العنوان سيُضاف لاحقاً', hours:'أوقات العمل ستُضاف لاحقاً', open:'أوقات العمل ستُضاف لاحقاً', closed:'غير متاح حالياً', unavailable:'غير متوفر الآن', search:'ابحث في القائمة', menu:'القائمة', all:'الكل', contact:'زورونا', follow:'تابعوا الدار', hoursTitle:'أوقات العمل', detail:'عن هذا المنتج', loading:'القائمة قادمة…', noResults:'لا توجد نتائج مطابقة لبحثك.', footer:'قائمة لاستـرادا كافيه ريستو.', cached:'القائمة متاحة دون اتصال', adminEntry:'محرر القائمة', close:'إغلاق', itinerary:'المسار سيُضاف لاحقاً', phoneTitle:'الهاتف', phonePlaceholder:'الرقم سيُضاف لاحقاً', socialTitle:'التواصل الاجتماعي', socialPlaceholder:'الحساب سيُضاف لاحقاً', addressTitle:'العنوان' },
  en: { tagline:'Coffee, then a little pause.', intro:'A house menu, familiar favourites and the pleasure of taking your time.', address:'Address to be provided', hours:'Hours to be provided', open:'Hours to be provided', closed:'Temporarily unavailable', unavailable:'Not available right now', search:'Search the menu', menu:'The menu', all:'All', contact:'Find us', follow:'Follow along', hoursTitle:'Opening hours', detail:'About this product', loading:'The menu is on its way…', noResults:'Nothing matches your search.', footer:'The LASTRADA Café-Resto menu.', cached:'Menu available offline', adminEntry:'Menu editor', close:'Close', itinerary:'Directions to be provided', phoneTitle:'Phone', phonePlaceholder:'Number to be provided', socialTitle:'Social', socialPlaceholder:'Account to be provided', addressTitle:'Address' },
} as const;

export const adminText = {
  fr: { editor:'ÉDITEUR LOCAL · LASTRADA', categories:'Les rubriques', products:'Les produits', preview:'Aperçu client', tabCategories:'Catégories', tabProducts:'Produits', tabPreview:'Aperçu', add:'Ajouter', order:'Utilisez les flèches pour réordonner les rubriques.', productNote:'Prix en dinars tunisiens · carte sans commande.', sections:'Rubriques de la carte', items:'produits', position:'position', available:'Disponible', unavailable:'Indisponible', view:'Voir la carte', reset:'Restaurer la démo', resetConfirm:'Réinitialiser la carte ?', resetMessage:'Les modifications locales seront remplacées par le menu de démonstration.', installTitle:'Votre carte, à portée de pouce.', installBody:'Ajoutez LASTRADA à l’écran d’accueil depuis le menu de votre navigateur.', localTitle:'Données de démonstration', localBody:'Enregistrées uniquement dans ce navigateur.', loginEyebrow:'ESPACE ÉDITEUR · DÉMO LOCALE', loginTitle:'La carte, à portée de main.', loginBody:'Accès de démonstration local uniquement. Aucune connexion à un service externe.', email:'Adresse e-mail démo', password:'Mot de passe démo', loginHint:'Démo uniquement : toute adresse et tout mot de passe non vides ouvrent cet espace sur cet appareil.', enter:'Entrer dans l’éditeur', back:'Retour à la carte', addCategory:'Ajouter une catégorie', editCategory:'Modifier la catégorie', newCategory:'Nouvelle catégorie', categoryName:'Nom en français', categoryNote:'Les traductions restent conservées pour les catégories déjà présentes. Les nouvelles catégories apparaissent en français dans les autres langues.', emptyCategory:'Aucune catégorie. Ajoutez la première.', deleteCategory:'Supprimer cette catégorie ?', deleteProduct:'Supprimer ce produit ?', removedCategory:'La catégorie et ses produits seront retirés de la carte.', removedProduct:'Le produit sera retiré de la carte.', cancel:'Annuler', save:'Enregistrer', editProduct:'Modifier le produit', newProduct:'Nouveau produit', image:'Ajouter une photo depuis cet appareil', imageNote:'La photo est recadrée localement en aperçu WebP de 800 px. Elle reste sur cet appareil et n’est pas téléversée.', name:'Nom en français', price:'Prix · TND', category:'Catégorie', description:'Description', descriptionHint:'Une phrase, quelques saveurs.', availableToggle:'Disponible sur la carte', confirm:'CONFIRMATION', delete:'Supprimer', noProducts:'Aucun produit pour le moment.', createCategoryFirst:'Créez une catégorie avant d’ajouter un produit.', createCategory:'Créer une catégorie', previewTitle:'À quoi ressemble la carte', previewBody:'La vue visiteur, avec vos changements locaux.', previewLocal:'LOCAL · V1', moveFirst:'Mettre en premier', quickAdd:'Ajouter un produit' },
  en: { editor:'LOCAL EDITOR · LASTRADA', categories:'Categories', products:'Products', preview:'Customer preview', tabCategories:'Categories', tabProducts:'Products', tabPreview:'Preview', add:'Add', order:'Use the arrows to reorder categories.', productNote:'Prices in Tunisian dinars · browsing only.', sections:'Menu categories', items:'products', position:'position', available:'Available', unavailable:'Unavailable', view:'View menu', reset:'Reset demo', resetConfirm:'Reset this menu?', resetMessage:'Local edits will be replaced by the demo menu.', installTitle:'Your menu, close at hand.', installBody:'Add LASTRADA to your home screen from your browser menu.', localTitle:'Demo data', localBody:'Saved only in this browser.', loginEyebrow:'LOCAL DEMO EDITOR', loginTitle:'Your menu, close at hand.', loginBody:'Local demo access only. No external service is connected.', email:'Demo email address', password:'Demo password', loginHint:'Demo only: any non-empty email and password open this editor on this device.', enter:'Enter editor', back:'Back to the menu', addCategory:'Add category', editCategory:'Edit category', newCategory:'New category', categoryName:'Name in French', categoryNote:'Translations remain for existing categories. New categories appear in French in other languages.', emptyCategory:'No categories yet. Add the first one.', deleteCategory:'Delete this category?', deleteProduct:'Delete this product?', removedCategory:'The category and its products will be removed from the menu.', removedProduct:'The product will be removed from the menu.', cancel:'Cancel', save:'Save changes', editProduct:'Edit product', newProduct:'New product', image:'Choose a photo from this device', imageNote:'The photo is locally cropped to an 800 px WebP preview. It stays on this device and is not uploaded.', name:'Name in French', price:'Price · TND', category:'Category', description:'Description', descriptionHint:'A line or two about the flavours.', availableToggle:'Available on the menu', confirm:'CONFIRMATION', delete:'Delete', noProducts:'No products here yet.', createCategoryFirst:'Create a category before adding products.', createCategory:'Create a category', previewTitle:'The menu as guests see it', previewBody:'Customer view, with your local changes.', previewLocal:'LOCAL · V1', moveFirst:'Move to first', quickAdd:'Add a product' },
  ar: { editor:'محرر محلي · لاستـرادا', categories:'الفئات', products:'المنتجات', preview:'معاينة الزائر', tabCategories:'الفئات', tabProducts:'المنتجات', tabPreview:'معاينة', add:'إضافة', order:'استخدم الأسهم لإعادة ترتيب الفئات.', productNote:'الأسعار بالدينار التونسي · عرض القائمة فقط.', sections:'فئات القائمة', items:'منتجات', position:'الترتيب', available:'متوفر', unavailable:'غير متوفر', view:'عرض القائمة', reset:'استعادة التجربة', resetConfirm:'استعادة القائمة؟', resetMessage:'ستستبدل التعديلات المحلية بقائمة التجربة.', installTitle:'قائمتك دائماً قريبة.', installBody:'أضف لاستـرادا إلى الشاشة الرئيسية من قائمة المتصفح.', localTitle:'بيانات تجريبية', localBody:'محفوظة على هذا المتصفح فقط.', loginEyebrow:'محرر محلي تجريبي', loginTitle:'قائمتك في متناول يدك.', loginBody:'دخول تجريبي محلي فقط. لا يوجد اتصال بخدمات خارجية.', email:'البريد الإلكتروني التجريبي', password:'كلمة مرور تجريبية', loginHint:'للتجربة فقط: أي بريد وكلمة مرور غير فارغين يفتحان المحرر على هذا الجهاز.', enter:'الدخول إلى المحرر', back:'العودة إلى القائمة', addCategory:'إضافة فئة', editCategory:'تعديل الفئة', newCategory:'فئة جديدة', categoryName:'الاسم بالفرنسية', categoryNote:'تبقى الترجمات للفئات الموجودة. تظهر الفئات الجديدة بالفرنسية في اللغات الأخرى.', emptyCategory:'لا توجد فئات. أضف الأولى.', deleteCategory:'حذف هذه الفئة؟', deleteProduct:'حذف هذا المنتج؟', removedCategory:'سيتم حذف الفئة ومنتجاتها من القائمة.', removedProduct:'سيتم حذف المنتج من القائمة.', cancel:'إلغاء', save:'حفظ', editProduct:'تعديل المنتج', newProduct:'منتج جديد', image:'اختر صورة من هذا الجهاز', imageNote:'تُقص الصورة محلياً إلى معاينة WebP بعرض 800 بكسل. تبقى على هذا الجهاز ولا تُرفع.', name:'الاسم بالفرنسية', price:'السعر · دينار', category:'الفئة', description:'الوصف', descriptionHint:'جملة عن النكهات.', availableToggle:'متوفر في القائمة', confirm:'تأكيد', delete:'حذف', noProducts:'لا توجد منتجات هنا بعد.', createCategoryFirst:'أنشئ فئة قبل إضافة المنتجات.', createCategory:'إنشاء فئة', previewTitle:'القائمة كما يراها الزوار', previewBody:'عرض الزوار مع تعديلاتك المحلية.', previewLocal:'محلي · ١', moveFirst:'نقل إلى البداية', quickAdd:'إضافة منتج' },
} as const;

export function translated(text: string, translations: LocalizedText | undefined, locale: Locale) {
  return (translations?.[locale] || text);
}
